//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileConference.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int LinkId { get; set; }
        public Nullable<int> User { get; set; }
        public string Message { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsDeleted { get; set; }
        public int Type { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual CommentType CommentType { get; set; }
    }
}
