//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileConference.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Sponsors = new HashSet<Sponsor>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Avatar { get; set; }
        public string Site { get; set; }
        public Nullable<int> Creator { get; set; }
        public bool IsShowed { get; set; }
        public Nullable<int> Rank { get; set; }
    
        public virtual PictureStore PictureStore { get; set; }
        public virtual ICollection<Sponsor> Sponsors { get; set; }
    }
}
