//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileConference.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventProfile
    {
        public EventProfile()
        {
            this.Awards = new HashSet<Award>();
            this.EventProfile1 = new HashSet<EventProfile>();
            this.ExpertForEvents = new HashSet<ExpertForEvent>();
            this.Ideas = new HashSet<Idea>();
            this.News = new HashSet<News>();
            this.GroupIdeas = new HashSet<GroupIdea>();
            this.Materials = new HashSet<Material>();
            this.Platforms = new HashSet<Platform>();
            this.Regions = new HashSet<Region>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Desctiption { get; set; }
        public int Type { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Avatar { get; set; }
    
        public virtual ICollection<Award> Awards { get; set; }
        public virtual ICollection<EventProfile> EventProfile1 { get; set; }
        public virtual EventProfile EventProfile2 { get; set; }
        public virtual PictureStore PictureStore { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual ICollection<ExpertForEvent> ExpertForEvents { get; set; }
        public virtual ICollection<Idea> Ideas { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<GroupIdea> GroupIdeas { get; set; }
        public virtual ICollection<Material> Materials { get; set; }
        public virtual ICollection<Platform> Platforms { get; set; }
        public virtual ICollection<Region> Regions { get; set; }
    }
}
