//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileConference.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertForEvent
    {
        public int Expert { get; set; }
        public int Event { get; set; }
        public int Platform { get; set; }
    
        public virtual EventProfile EventProfile { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual Platform Platform1 { get; set; }
    }
}
