//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileConference.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idea
    {
        public Idea()
        {
            this.RealizedPlatforms = new HashSet<RealizedPlatform>();
            this.StudentGroups = new HashSet<StudentGroup>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> MentorId { get; set; }
        public Nullable<int> GroupIdeaId { get; set; }
        public Nullable<int> EventId { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Avatar { get; set; }
    
        public virtual EventProfile EventProfile { get; set; }
        public virtual GroupIdea GroupIdea { get; set; }
        public virtual PictureStore PictureStore { get; set; }
        public virtual Mentor Mentor { get; set; }
        public virtual ICollection<RealizedPlatform> RealizedPlatforms { get; set; }
        public virtual ICollection<StudentGroup> StudentGroups { get; set; }
    }
}
