//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileConference.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.EventProfiles = new HashSet<EventProfile>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> PlatformId { get; set; }
        public Nullable<int> PictureId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Link { get; set; }
    
        public virtual Platform Platform { get; set; }
        public virtual ICollection<EventProfile> EventProfiles { get; set; }
    }
}
