//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileConference.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Award> Awards { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<CommentType> CommentTypes { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<EventProfile> EventProfiles { get; set; }
        public DbSet<EventType> EventTypes { get; set; }
        public DbSet<ExpertForEvent> ExpertForEvents { get; set; }
        public DbSet<GroupIdea> GroupIdeas { get; set; }
        public DbSet<Idea> Ideas { get; set; }
        public DbSet<Material> Materials { get; set; }
        public DbSet<Mentor> Mentors { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<Option> Options { get; set; }
        public DbSet<PictureAssign> PictureAssigns { get; set; }
        public DbSet<PictureAssignType> PictureAssignTypes { get; set; }
        public DbSet<PictureStore> PictureStores { get; set; }
        public DbSet<Platform> Platforms { get; set; }
        public DbSet<RealizedPlatform> RealizedPlatforms { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<Skill> Skills { get; set; }
        public DbSet<Sponsor> Sponsors { get; set; }
        public DbSet<StatusRealizedPlatform> StatusRealizedPlatforms { get; set; }
        public DbSet<StatusStudent> StatusStudents { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentGroup> StudentGroups { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<UserRestoreInfo> UserRestoreInfoes { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
