//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileConference.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int EventId { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<int> ForRoles { get; set; }
    
        public virtual EventProfile EventProfile { get; set; }
    }
}
