//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileConference.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureStore
    {
        public PictureStore()
        {
            this.Companies = new HashSet<Company>();
            this.EventProfiles = new HashSet<EventProfile>();
            this.Ideas = new HashSet<Idea>();
            this.PictureAssigns = new HashSet<PictureAssign>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        public string Picture { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<EventProfile> EventProfiles { get; set; }
        public virtual ICollection<Idea> Ideas { get; set; }
        public virtual ICollection<PictureAssign> PictureAssigns { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
