//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileConference.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platform
    {
        public Platform()
        {
            this.ExpertForEvents = new HashSet<ExpertForEvent>();
            this.Materials = new HashSet<Material>();
            this.RealizedPlatforms = new HashSet<RealizedPlatform>();
            this.EventProfiles = new HashSet<EventProfile>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
        public string Description { get; set; }
        public Nullable<int> Picture { get; set; }
    
        public virtual ICollection<ExpertForEvent> ExpertForEvents { get; set; }
        public virtual ICollection<Material> Materials { get; set; }
        public virtual ICollection<RealizedPlatform> RealizedPlatforms { get; set; }
        public virtual ICollection<EventProfile> EventProfiles { get; set; }
    }
}
