//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileConference.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.StudentGroups = new HashSet<StudentGroup>();
        }
    
        public int Id { get; set; }
        public string University { get; set; }
        public Nullable<short> YearBegining { get; set; }
        public Nullable<short> YearGraduating { get; set; }
        public string Faculty { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<StudentGroup> StudentGroups { get; set; }
    }
}
