//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileConference.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentGroup
    {
        public int StudentId { get; set; }
        public int IdeaId { get; set; }
        public int StatusStudentId { get; set; }
    
        public virtual Idea Idea { get; set; }
        public virtual StatusStudent StatusStudent { get; set; }
        public virtual Student Student { get; set; }
    }
}
