//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileConference.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Comments = new HashSet<Comment>();
            this.ExpertForEvents = new HashSet<ExpertForEvent>();
            this.PictureAssigns = new HashSet<PictureAssign>();
            this.Skills = new HashSet<Skill>();
            this.webpages_Roles1 = new HashSet<webpages_Roles>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SecondName { get; set; }
        public string Login { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public Nullable<int> Avatar { get; set; }
        public Nullable<int> WishedRole { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DateActivity { get; set; }
        public string Description { get; set; }
        public string PlaceJob { get; set; }
        public bool EmailConfirmation { get; set; }
        public int Tips { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<ExpertForEvent> ExpertForEvents { get; set; }
        public virtual Mentor Mentor { get; set; }
        public virtual ICollection<PictureAssign> PictureAssigns { get; set; }
        public virtual PictureStore PictureStore { get; set; }
        public virtual Sponsor Sponsor { get; set; }
        public virtual Student Student { get; set; }
        public virtual webpages_Roles webpages_Roles { get; set; }
        public virtual UserRestoreInfo UserRestoreInfo { get; set; }
        public virtual ICollection<Skill> Skills { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles1 { get; set; }
    }
}
